DATA:
  USE_MOTION: True

MODEL:
  NAME: "video-bk"
  BERT_TYPE: "ROBERTA"
  BERT_NAME: "roberta-large"
  IMG_ENCODER: "efficientnet-b3"
  car_idloss: True
  mo_idloss: True
  share_idloss: True
TRAIN: 
  BATCH_SIZE: 8